//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasrafTakibi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masraf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masraf()
        {
            this.ToplamMasraf = new HashSet<ToplamMasraf>();
        }
    
        public int MasrafID { get; set; }
        public string masrafSahibi { get; set; }
        public string MasrafTipi { get; set; }
        public string MasrafMiktari { get; set; }
        public Nullable<System.DateTime> MasrafTarihi { get; set; }
        public string MasrafAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToplamMasraf> ToplamMasraf { get; set; }
    }
}
