//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasrafTakibi.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasrafDBEntities : DbContext
    {
        public MasrafDBEntities()
            : base("name=MasrafDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calisan> Calisan { get; set; }
        public virtual DbSet<KullaniciGiris> KullaniciGiris { get; set; }
        public virtual DbSet<Masraf> Masraf { get; set; }
        public virtual DbSet<ToplamMasraf> ToplamMasraf { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }
    }
}
