//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasrafTakibi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToplamMasraf
    {
        public int ToplamMasrafID { get; set; }
        public int KullaniciID { get; set; }
        public int CalisanID { get; set; }
        public int YoneticiID { get; set; }
        public int MasrafID { get; set; }
    
        public virtual Calisan Calisan { get; set; }
        public virtual KullaniciGiris KullaniciGiris { get; set; }
        public virtual Masraf Masraf { get; set; }
        public virtual Yonetici Yonetici { get; set; }
    }
}
